from pathlib import Path

path = Path('lib/main.dart')
src = path.read_text(encoding='utf-8')

old = '''                LayoutBuilder(\n                  builder: (BuildContext context, BoxConstraints constraints) {\n                    const double gap = 13;\n                    const double minimumCardHeight = 156;\n                    final double cardWidth = (constraints.maxWidth - gap) / 2;\n                    final double ratio =\n                        math.min(1.0, cardWidth / minimumCardHeight);\n                    return GridView.count(\n                      crossAxisCount: 2,\n                      crossAxisSpacing: gap,\n                      mainAxisSpacing: gap,\n                      shrinkWrap: true,\n                      physics: const NeverScrollableScrollPhysics(),\n                      childAspectRatio: ratio,\n                      children: <Widget>[\n                        _MetricCard(\n                          icon: Icons.volunteer_activism_rounded,\n                          label: 'To Receive (+)',\n                          value: _money(totals.toReceive),\n                          color: appleGreen,\n                        ),\n                        _MetricCard(\n                          icon: Icons.request_quote_rounded,\n                          label: 'To Pay (-)',\n                          value: _money(totals.toPay),\n                          color: appleRed,\n                        ),\n                        _MetricCard(\n                          icon: Icons.receipt_long_rounded,\n                          label: 'Month Expense',\n                          value: _money(totals.monthExpense),\n                          color: diaryOrange,\n                        ),\n                        _MetricCard(\n                          icon: Icons.trending_up_rounded,\n                          label: 'Month Profit',\n                          value: _signedMoney(totals.monthProfit),\n                          color: appleBlue,\n                        ),\n                      ],\n                    );\n                  },\n                ),'''

new = '''                LayoutBuilder(\n                  builder: (BuildContext context, BoxConstraints constraints) {\n                    const double gap = 13;\n                    const double minimumCardHeight = 156;\n                    final double cardWidth = (constraints.maxWidth - gap) / 2;\n                    final double cardHeight = math.max(\n                      minimumCardHeight,\n                      cardWidth,\n                    );\n\n                    Widget lockedCard(Widget child) => SizedBox(\n                          width: cardWidth,\n                          height: cardHeight,\n                          child: child,\n                        );\n\n                    return Column(\n                      mainAxisSize: MainAxisSize.min,\n                      children: <Widget>[\n                        Row(\n                          children: <Widget>[\n                            lockedCard(\n                              _MetricCard(\n                                icon: Icons.volunteer_activism_rounded,\n                                label: 'To Receive (+)',\n                                value: _money(totals.toReceive),\n                                color: appleGreen,\n                              ),\n                            ),\n                            const SizedBox(width: gap),\n                            lockedCard(\n                              _MetricCard(\n                                icon: Icons.request_quote_rounded,\n                                label: 'To Pay (-)',\n                                value: _money(totals.toPay),\n                                color: appleRed,\n                              ),\n                            ),\n                          ],\n                        ),\n                        const SizedBox(height: gap),\n                        Row(\n                          children: <Widget>[\n                            lockedCard(\n                              _MetricCard(\n                                icon: Icons.receipt_long_rounded,\n                                label: 'Month Expense',\n                                value: _money(totals.monthExpense),\n                                color: diaryOrange,\n                              ),\n                            ),\n                            const SizedBox(width: gap),\n                            lockedCard(\n                              _MetricCard(\n                                icon: Icons.trending_up_rounded,\n                                label: 'Month Profit',\n                                value: _signedMoney(totals.monthProfit),\n                                color: appleBlue,\n                              ),\n                            ),\n                          ],\n                        ),\n                      ],\n                    );\n                  },\n                ),'''

if src.count(old) != 1:
    raise SystemExit(f'Dashboard adaptive grid block count={src.count(old)}')
src = src.replace(old, new, 1)

path.write_text(src, encoding='utf-8')
print('PATCH_OK dashboard cards now use explicit locked width/height independent of amount')
