name: voice_ludo_masti
description: A fun local multiplayer Ludo game with an offline voice-controlled dice.
publish_to: "none"
version: 1.1.0+2

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.32.0"

dependencies:
  flutter:
    sdk: flutter
  vosk_flutter_service: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/models/vosk-model-small-hi-0.22.zip
